[2025-04-01T17:47:24.961+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-13T22:00:00+00:00 [queued]>
[2025-04-01T17:47:24.981+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-13T22:00:00+00:00 [queued]>
[2025-04-01T17:47:24.981+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-01T17:47:25.010+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-13 22:00:00+00:00
[2025-04-01T17:47:25.020+0000] {standard_task_runner.py:60} INFO - Started process 819 to run task
[2025-04-01T17:47:25.026+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-13T22:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpgcgkz2_4']
[2025-04-01T17:47:25.029+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask gen_data_daily
[2025-04-01T17:47:25.127+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-13T22:00:00+00:00 [running]> on host 0b0a92439eeb
[2025-04-01T17:47:25.313+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T22:00:00+00:00'
[2025-04-01T17:47:25.315+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-01T17:47:25.316+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-14\n        ']
[2025-04-01T17:47:25.335+0000] {subprocess.py:86} INFO - Output:
[2025-04-01T17:47:26.544+0000] {subprocess.py:93} INFO - Successfully inserted 5000 rows into transaction_data table at 2025-03-14
[2025-04-01T17:47:26.545+0000] {subprocess.py:93} INFO - Table contains 65000 rows
[2025-04-01T17:47:26.548+0000] {subprocess.py:93} INFO - Data generation and insertion complete at 2025-03-14
[2025-04-01T17:47:26.655+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-01T17:47:26.700+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250313T220000, start_date=20250401T174724, end_date=20250401T174726
[2025-04-01T17:47:26.754+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-01T17:47:26.782+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T17:08:58.852+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-13T22:00:00+00:00 [queued]>
[2025-04-28T17:08:58.884+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-13T22:00:00+00:00 [queued]>
[2025-04-28T17:08:58.884+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-28T17:08:58.902+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-13 22:00:00+00:00
[2025-04-28T17:08:58.909+0000] {standard_task_runner.py:60} INFO - Started process 44376 to run task
[2025-04-28T17:08:58.917+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-13T22:00:00+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpclpivcee']
[2025-04-28T17:08:58.919+0000] {standard_task_runner.py:88} INFO - Job 165: Subtask gen_data_daily
[2025-04-28T17:08:59.009+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-13T22:00:00+00:00 [running]> on host 45b38884c639
[2025-04-28T17:08:59.079+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-04-28T17:08:59.154+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T22:00:00+00:00'
[2025-04-28T17:08:59.156+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-28T17:08:59.159+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/step_1_1_gen_transaction_data.py 2025-03-14\n        ']
[2025-04-28T17:08:59.180+0000] {subprocess.py:86} INFO - Output:
[2025-04-28T17:09:00.428+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-28T17:09:00.467+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250313T220000, start_date=20250428T170858, end_date=20250428T170900
[2025-04-28T17:09:00.501+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T17:09:00.725+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
