[2025-04-01T17:47:01.767+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-04T22:00:00+00:00 [queued]>
[2025-04-01T17:47:01.779+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-04T22:00:00+00:00 [queued]>
[2025-04-01T17:47:01.779+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-01T17:47:01.799+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-04 22:00:00+00:00
[2025-04-01T17:47:01.807+0000] {standard_task_runner.py:60} INFO - Started process 712 to run task
[2025-04-01T17:47:01.814+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-04T22:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpdh_y2bpt']
[2025-04-01T17:47:01.816+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask gen_data_daily
[2025-04-01T17:47:01.887+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-04T22:00:00+00:00 [running]> on host 0b0a92439eeb
[2025-04-01T17:47:02.088+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-04T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-04T22:00:00+00:00'
[2025-04-01T17:47:02.089+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-01T17:47:02.094+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-05\n        ']
[2025-04-01T17:47:02.122+0000] {subprocess.py:86} INFO - Output:
[2025-04-01T17:47:03.040+0000] {subprocess.py:93} INFO - Successfully inserted 5000 rows into transaction_data table at 2025-03-05
[2025-04-01T17:47:03.040+0000] {subprocess.py:93} INFO - Table contains 20000 rows
[2025-04-01T17:47:03.041+0000] {subprocess.py:93} INFO - Data generation and insertion complete at 2025-03-05
[2025-04-01T17:47:03.131+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-01T17:47:03.175+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250304T220000, start_date=20250401T174701, end_date=20250401T174703
[2025-04-01T17:47:03.201+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-01T17:47:03.231+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T17:08:37.231+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-04T22:00:00+00:00 [queued]>
[2025-04-28T17:08:37.285+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-04T22:00:00+00:00 [queued]>
[2025-04-28T17:08:37.285+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-28T17:08:37.314+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-04 22:00:00+00:00
[2025-04-28T17:08:37.324+0000] {standard_task_runner.py:60} INFO - Started process 44259 to run task
[2025-04-28T17:08:37.331+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-04T22:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmp1mqkvsci']
[2025-04-28T17:08:37.333+0000] {standard_task_runner.py:88} INFO - Job 156: Subtask gen_data_daily
[2025-04-28T17:08:37.448+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-04T22:00:00+00:00 [running]> on host 45b38884c639
[2025-04-28T17:08:37.530+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-04-28T17:08:37.599+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-04T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-04T22:00:00+00:00'
[2025-04-28T17:08:37.601+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-28T17:08:37.604+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/step_1_1_gen_transaction_data.py 2025-03-05\n        ']
[2025-04-28T17:08:37.679+0000] {subprocess.py:86} INFO - Output:
[2025-04-28T17:08:39.524+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-28T17:08:39.629+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250304T220000, start_date=20250428T170837, end_date=20250428T170839
[2025-04-28T17:08:39.695+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T17:08:39.819+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
