[2025-04-01T17:47:14.759+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-09T22:00:00+00:00 [queued]>
[2025-04-01T17:47:14.770+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-09T22:00:00+00:00 [queued]>
[2025-04-01T17:47:14.770+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-01T17:47:14.791+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-09 22:00:00+00:00
[2025-04-01T17:47:14.796+0000] {standard_task_runner.py:60} INFO - Started process 767 to run task
[2025-04-01T17:47:14.802+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-09T22:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpn62nls6k']
[2025-04-01T17:47:14.803+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask gen_data_daily
[2025-04-01T17:47:14.892+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-09T22:00:00+00:00 [running]> on host 0b0a92439eeb
[2025-04-01T17:47:15.033+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-09T22:00:00+00:00'
[2025-04-01T17:47:15.034+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-01T17:47:15.036+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-10\n        ']
[2025-04-01T17:47:15.056+0000] {subprocess.py:86} INFO - Output:
[2025-04-01T17:47:16.149+0000] {subprocess.py:93} INFO - Successfully inserted 5000 rows into transaction_data table at 2025-03-10
[2025-04-01T17:47:16.149+0000] {subprocess.py:93} INFO - Table contains 45000 rows
[2025-04-01T17:47:16.150+0000] {subprocess.py:93} INFO - Data generation and insertion complete at 2025-03-10
[2025-04-01T17:47:16.264+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-01T17:47:16.308+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250309T220000, start_date=20250401T174714, end_date=20250401T174716
[2025-04-01T17:47:16.346+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-01T17:47:16.375+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T17:08:49.816+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-09T22:00:00+00:00 [queued]>
[2025-04-28T17:08:49.846+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-09T22:00:00+00:00 [queued]>
[2025-04-28T17:08:49.847+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-28T17:08:49.887+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-09 22:00:00+00:00
[2025-04-28T17:08:49.898+0000] {standard_task_runner.py:60} INFO - Started process 44324 to run task
[2025-04-28T17:08:49.900+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-09T22:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpisq13cry']
[2025-04-28T17:08:49.908+0000] {standard_task_runner.py:88} INFO - Job 161: Subtask gen_data_daily
[2025-04-28T17:08:50.008+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-09T22:00:00+00:00 [running]> on host 45b38884c639
[2025-04-28T17:08:50.095+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-04-28T17:08:50.152+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-09T22:00:00+00:00'
[2025-04-28T17:08:50.154+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-28T17:08:50.155+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/step_1_1_gen_transaction_data.py 2025-03-10\n        ']
[2025-04-28T17:08:50.171+0000] {subprocess.py:86} INFO - Output:
[2025-04-28T17:08:51.860+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-28T17:08:51.997+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250309T220000, start_date=20250428T170849, end_date=20250428T170851
[2025-04-28T17:08:52.118+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T17:08:52.200+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
