[2025-04-22T17:17:31.028+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_lxw_fts.calculate_fts scheduled__2025-03-10T23:00:00+00:00 [queued]>
[2025-04-22T17:17:31.104+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_lxw_fts.calculate_fts scheduled__2025-03-10T23:00:00+00:00 [queued]>
[2025-04-22T17:17:31.105+0000] {taskinstance.py:2171} INFO - Starting attempt 5 of 6
[2025-04-22T17:17:31.151+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): calculate_fts> on 2025-03-10 23:00:00+00:00
[2025-04-22T17:17:31.161+0000] {standard_task_runner.py:60} INFO - Started process 4276 to run task
[2025-04-22T17:17:31.167+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_lxw_fts', 'calculate_fts', 'scheduled__2025-03-10T23:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/gen_lxw_fts.py', '--cfg-path', '/tmp/tmpz12lyv2y']
[2025-04-22T17:17:31.169+0000] {standard_task_runner.py:88} INFO - Job 146: Subtask calculate_fts
[2025-04-22T17:17:31.284+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_lxw_fts.calculate_fts scheduled__2025-03-10T23:00:00+00:00 [running]> on host 45b38884c639
[2025-04-22T17:17:31.496+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-04-22T17:17:31.606+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_lxw_fts' AIRFLOW_CTX_TASK_ID='calculate_fts' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T23:00:00+00:00'
[2025-04-22T17:17:31.608+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-22T17:17:31.609+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/2_calculate_features.py 2025-03-11\n        ']
[2025-04-22T17:17:31.660+0000] {subprocess.py:86} INFO - Output:
[2025-04-22T17:17:54.860+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-04-22T17:17:55.216+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-04-22T17:17:55.217+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-04-22T17:17:55.224+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-04-22T17:17:55.224+0000] {subprocess.py:93} INFO - io.delta#delta-core_2.12 added as a dependency
[2025-04-22T17:17:55.224+0000] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-04-22T17:17:55.224+0000] {subprocess.py:93} INFO - com.amazonaws#aws-java-sdk-bundle added as a dependency
[2025-04-22T17:17:55.225+0000] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2025-04-22T17:17:55.226+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-4c20db34-a16e-47bb-a632-7a10f84de2c7;1.0
[2025-04-22T17:17:55.226+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-04-22T17:17:55.749+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.4.1 in central
[2025-04-22T17:17:55.869+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.4.1 in central
[2025-04-22T17:17:55.927+0000] {subprocess.py:93} INFO - 	found org.apache.kafka#kafka-clients;3.3.2 in central
[2025-04-22T17:17:55.967+0000] {subprocess.py:93} INFO - 	found org.lz4#lz4-java;1.8.0 in central
[2025-04-22T17:17:56.017+0000] {subprocess.py:93} INFO - 	found org.xerial.snappy#snappy-java;1.1.10.1 in central
[2025-04-22T17:17:56.056+0000] {subprocess.py:93} INFO - 	found org.slf4j#slf4j-api;2.0.6 in central
[2025-04-22T17:17:56.099+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2025-04-22T17:17:56.137+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.4 in central
[2025-04-22T17:17:56.193+0000] {subprocess.py:93} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2025-04-22T17:17:56.227+0000] {subprocess.py:93} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-04-22T17:17:56.251+0000] {subprocess.py:93} INFO - 	found org.apache.commons#commons-pool2;2.11.1 in central
[2025-04-22T17:17:56.272+0000] {subprocess.py:93} INFO - 	found io.delta#delta-core_2.12;2.4.0 in central
[2025-04-22T17:17:56.292+0000] {subprocess.py:93} INFO - 	found io.delta#delta-storage;2.4.0 in central
[2025-04-22T17:17:56.305+0000] {subprocess.py:93} INFO - 	found org.antlr#antlr4-runtime;4.9.3 in central
[2025-04-22T17:17:56.369+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.2 in central
[2025-04-22T17:17:56.386+0000] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2025-04-22T17:17:56.484+0000] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.12.261 in central
[2025-04-22T17:17:56.593+0000] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.5.1 in central
[2025-04-22T17:17:56.646+0000] {subprocess.py:93} INFO - 	found org.checkerframework#checker-qual;3.5.0 in central
[2025-04-22T17:17:56.769+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 1446ms :: artifacts dl 97ms
[2025-04-22T17:17:56.769+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-04-22T17:17:56.770+0000] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.12.261 from central in [default]
[2025-04-22T17:17:56.771+0000] {subprocess.py:93} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-04-22T17:17:56.771+0000] {subprocess.py:93} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2025-04-22T17:17:56.772+0000] {subprocess.py:93} INFO - 	io.delta#delta-core_2.12;2.4.0 from central in [default]
[2025-04-22T17:17:56.789+0000] {subprocess.py:93} INFO - 	io.delta#delta-storage;2.4.0 from central in [default]
[2025-04-22T17:17:56.789+0000] {subprocess.py:93} INFO - 	org.antlr#antlr4-runtime;4.9.3 from central in [default]
[2025-04-22T17:17:56.790+0000] {subprocess.py:93} INFO - 	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-04-22T17:17:56.790+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.2 from central in [default]
[2025-04-22T17:17:56.790+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.4 from central in [default]
[2025-04-22T17:17:56.791+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.4 from central in [default]
[2025-04-22T17:17:56.791+0000] {subprocess.py:93} INFO - 	org.apache.kafka#kafka-clients;3.3.2 from central in [default]
[2025-04-22T17:17:56.792+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.4.1 from central in [default]
[2025-04-22T17:17:56.792+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.4.1 from central in [default]
[2025-04-22T17:17:56.792+0000] {subprocess.py:93} INFO - 	org.checkerframework#checker-qual;3.5.0 from central in [default]
[2025-04-22T17:17:56.793+0000] {subprocess.py:93} INFO - 	org.lz4#lz4-java;1.8.0 from central in [default]
[2025-04-22T17:17:56.793+0000] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.5.1 from central in [default]
[2025-04-22T17:17:56.793+0000] {subprocess.py:93} INFO - 	org.slf4j#slf4j-api;2.0.6 from central in [default]
[2025-04-22T17:17:56.793+0000] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2025-04-22T17:17:56.793+0000] {subprocess.py:93} INFO - 	org.xerial.snappy#snappy-java;1.1.10.1 from central in [default]
[2025-04-22T17:17:56.794+0000] {subprocess.py:93} INFO - 	:: evicted modules:
[2025-04-22T17:17:56.794+0000] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.11.1026 by [com.amazonaws#aws-java-sdk-bundle;1.12.261] in [default]
[2025-04-22T17:17:56.794+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-04-22T17:17:56.794+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-04-22T17:17:56.794+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-04-22T17:17:56.794+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-04-22T17:17:56.794+0000] {subprocess.py:93} INFO - 	|      default     |   20  |   0   |   0   |   1   ||   19  |   0   |
[2025-04-22T17:17:56.795+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-04-22T17:17:56.795+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-4c20db34-a16e-47bb-a632-7a10f84de2c7
[2025-04-22T17:17:56.795+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-04-22T17:17:56.800+0000] {subprocess.py:93} INFO - 	0 artifacts copied, 19 already retrieved (0kB/18ms)
[2025-04-22T17:17:58.137+0000] {subprocess.py:93} INFO - 25/04/22 17:17:58 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-04-22T17:17:58.896+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-04-22T17:17:58.902+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-04-22T17:18:04.778+0000] {subprocess.py:93} INFO - 25/04/22 17:18:04 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-04-22T17:18:35.372+0000] {subprocess.py:93} INFO - 25/04/22 17:18:35 ERROR Inbox: Ignoring error
[2025-04-22T17:18:35.388+0000] {subprocess.py:93} INFO - java.lang.NullPointerException
[2025-04-22T17:18:35.388+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:600)
[2025-04-22T17:18:35.390+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:123)
[2025-04-22T17:18:35.391+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2025-04-22T17:18:35.391+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2025-04-22T17:18:35.391+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2025-04-22T17:18:35.391+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2025-04-22T17:18:35.391+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2025-04-22T17:18:35.391+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-04-22T17:18:35.391+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-04-22T17:18:35.398+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-04-22T17:18:35.398+0000] {subprocess.py:93} INFO - 25/04/22 17:18:35 WARN Executor: Issue communicating with driver in heartbeater
[2025-04-22T17:18:35.399+0000] {subprocess.py:93} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-04-22T17:18:35.401+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
[2025-04-22T17:18:35.402+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2025-04-22T17:18:35.403+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
[2025-04-22T17:18:35.404+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
[2025-04-22T17:18:35.404+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
[2025-04-22T17:18:35.405+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:641)
[2025-04-22T17:18:35.406+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1111)
[2025-04-22T17:18:35.407+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:244)
[2025-04-22T17:18:35.407+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-22T17:18:35.411+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2088)
[2025-04-22T17:18:35.412+0000] {subprocess.py:93} INFO - 	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
[2025-04-22T17:18:35.413+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2025-04-22T17:18:35.416+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[2025-04-22T17:18:35.417+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[2025-04-22T17:18:35.417+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-04-22T17:18:35.417+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-04-22T17:18:35.419+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-04-22T17:18:35.420+0000] {subprocess.py:93} INFO - Caused by: java.lang.NullPointerException
[2025-04-22T17:18:35.420+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:600)
[2025-04-22T17:18:35.421+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:123)
[2025-04-22T17:18:35.422+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2025-04-22T17:18:35.423+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2025-04-22T17:18:35.424+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2025-04-22T17:18:35.424+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2025-04-22T17:18:35.426+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2025-04-22T17:18:35.432+0000] {subprocess.py:93} INFO - 	... 3 more
[2025-04-22T17:18:44.830+0000] {subprocess.py:93} INFO - 25/04/22 17:18:44 ERROR Inbox: Ignoring error
[2025-04-22T17:18:44.844+0000] {subprocess.py:93} INFO - java.lang.NullPointerException
[2025-04-22T17:18:44.845+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:600)
[2025-04-22T17:18:44.846+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:123)
[2025-04-22T17:18:44.846+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2025-04-22T17:18:44.846+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2025-04-22T17:18:44.847+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2025-04-22T17:18:44.847+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2025-04-22T17:18:44.850+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2025-04-22T17:18:44.851+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-04-22T17:18:44.851+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-04-22T17:18:44.851+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-04-22T17:18:44.852+0000] {subprocess.py:93} INFO - 25/04/22 17:18:44 WARN Executor: Issue communicating with driver in heartbeater
[2025-04-22T17:18:44.852+0000] {subprocess.py:93} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-04-22T17:18:44.852+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
[2025-04-22T17:18:44.854+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2025-04-22T17:18:44.856+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
[2025-04-22T17:18:44.857+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
[2025-04-22T17:18:44.857+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
[2025-04-22T17:18:44.857+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:641)
[2025-04-22T17:18:44.857+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1111)
[2025-04-22T17:18:44.857+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:244)
[2025-04-22T17:18:44.857+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-22T17:18:44.857+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2088)
[2025-04-22T17:18:44.858+0000] {subprocess.py:93} INFO - 	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
[2025-04-22T17:18:44.859+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2025-04-22T17:18:44.859+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[2025-04-22T17:18:44.859+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[2025-04-22T17:18:44.859+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-04-22T17:18:44.859+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-04-22T17:18:44.860+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-04-22T17:18:44.860+0000] {subprocess.py:93} INFO - Caused by: java.lang.NullPointerException
[2025-04-22T17:18:44.860+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:600)
[2025-04-22T17:18:44.861+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:123)
[2025-04-22T17:18:44.861+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2025-04-22T17:18:44.861+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2025-04-22T17:18:44.861+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2025-04-22T17:18:44.861+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2025-04-22T17:18:44.861+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2025-04-22T17:18:44.862+0000] {subprocess.py:93} INFO - 	... 3 more
[2025-04-22T17:18:52.309+0000] {subprocess.py:93} INFO - 25/04/22 17:18:52 WARN SQLConf: The SQL config 'spark.sql.execution.arrow.fallback.enabled' has been deprecated in Spark v3.0 and may be removed in the future. Use 'spark.sql.execution.arrow.pyspark.fallback.enabled' instead of it.
[2025-04-22T17:18:52.310+0000] {subprocess.py:93} INFO - 25/04/22 17:18:52 WARN SQLConf: The SQL config 'spark.sql.execution.arrow.fallback.enabled' has been deprecated in Spark v3.0 and may be removed in the future. Use 'spark.sql.execution.arrow.pyspark.fallback.enabled' instead of it.
[2025-04-22T17:18:52.310+0000] {subprocess.py:93} INFO - 25/04/22 17:18:52 WARN SQLConf: The SQL config 'spark.sql.execution.arrow.fallback.enabled' has been deprecated in Spark v3.0 and may be removed in the future. Use 'spark.sql.execution.arrow.pyspark.fallback.enabled' instead of it.
[2025-04-22T17:19:14.782+0000] {subprocess.py:93} INFO - 25/04/22 17:19:14 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:19:45.926+0000] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 0) / 1][Stage 0:>                                                          (0 + 1) / 1]                                                                                25/04/22 17:19:45 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:19:46.178+0000] {subprocess.py:93} INFO - 25/04/22 17:19:46 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:20:03.649+0000] {subprocess.py:93} INFO - [Stage 1:>                                                          (0 + 1) / 1][Stage 1:>                  (0 + 1) / 1][Stage 2:>                  (0 + 1) / 1][Stage 1:>                                                          (0 + 1) / 1][Stage 4:>                                                          (0 + 1) / 1]                                                                                25/04/22 17:20:03 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:20:03.813+0000] {subprocess.py:93} INFO - 25/04/22 17:20:03 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:20:22.323+0000] {subprocess.py:93} INFO - [Stage 5:>                                                          (0 + 1) / 1][Stage 5:>                  (0 + 1) / 1][Stage 6:>                  (0 + 1) / 1][Stage 5:>                                                          (0 + 1) / 1][Stage 8:>                                                          (0 + 1) / 1]                                                                                25/04/22 17:20:22 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:20:22.503+0000] {subprocess.py:93} INFO - 25/04/22 17:20:22 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:20:44.286+0000] {subprocess.py:93} INFO - [Stage 16:>                 (0 + 1) / 1][Stage 17:>                 (0 + 1) / 1][Stage 16:>                                                         (0 + 1) / 1][Stage 19:>                                                         (0 + 5) / 5]                                                                                25/04/22 17:20:44 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2025-04-22T17:21:08.514+0000] {subprocess.py:93} INFO - 25/04/22 17:21:08 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:21:08.629+0000] {subprocess.py:93} INFO - 25/04/22 17:21:08 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:21:20.948+0000] {subprocess.py:93} INFO - [Stage 27:>                 (0 + 1) / 1][Stage 28:>                 (0 + 1) / 1]ERROR:root:Exception while sending command.
[2025-04-22T17:21:21.004+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-22T17:21:21.004+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 516, in send_command
[2025-04-22T17:21:21.005+0000] {subprocess.py:93} INFO -     raise Py4JNetworkError("Answer from Java side is empty")
[2025-04-22T17:21:21.005+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2025-04-22T17:21:21.005+0000] {subprocess.py:93} INFO - 
[2025-04-22T17:21:21.005+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2025-04-22T17:21:21.005+0000] {subprocess.py:93} INFO - 
[2025-04-22T17:21:21.006+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-22T17:21:21.006+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1038, in send_command
[2025-04-22T17:21:21.006+0000] {subprocess.py:93} INFO -     response = connection.send_command(command)
[2025-04-22T17:21:21.006+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 539, in send_command
[2025-04-22T17:21:21.006+0000] {subprocess.py:93} INFO -     raise Py4JNetworkError(
[2025-04-22T17:21:21.007+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2025-04-22T17:21:21.007+0000] {subprocess.py:93} INFO - 2025-03-04 2025-03-11
[2025-04-22T17:21:21.007+0000] {subprocess.py:93} INFO - Spark session initialized
[2025-04-22T17:21:21.008+0000] {subprocess.py:93} INFO - +------+--------------------+--------------------+---+-------------+-----------+
[2025-04-22T17:21:21.008+0000] {subprocess.py:93} INFO - |before|               after|              source| op|        ts_ms|transaction|
[2025-04-22T17:21:21.008+0000] {subprocess.py:93} INFO - +------+--------------------+--------------------+---+-------------+-----------+
[2025-04-22T17:21:21.008+0000] {subprocess.py:93} INFO - |  null|{1, user_000461, ...|{2.3.4.Final, pos...|  c|1745341450710|       null|
[2025-04-22T17:21:21.009+0000] {subprocess.py:93} INFO - |  null|{2, user_000113, ...|{2.3.4.Final, pos...|  c|1745341450735|       null|
[2025-04-22T17:21:21.009+0000] {subprocess.py:93} INFO - |  null|{3, user_000286, ...|{2.3.4.Final, pos...|  c|1745341450737|       null|
[2025-04-22T17:21:21.009+0000] {subprocess.py:93} INFO - |  null|{4, user_000402, ...|{2.3.4.Final, pos...|  c|1745341450738|       null|
[2025-04-22T17:21:21.009+0000] {subprocess.py:93} INFO - |  null|{5, user_000126, ...|{2.3.4.Final, pos...|  c|1745341450739|       null|
[2025-04-22T17:21:21.009+0000] {subprocess.py:93} INFO - +------+--------------------+--------------------+---+-------------+-----------+
[2025-04-22T17:21:21.009+0000] {subprocess.py:93} INFO - only showing top 5 rows
[2025-04-22T17:21:21.009+0000] {subprocess.py:93} INFO - 
[2025-04-22T17:21:21.009+0000] {subprocess.py:93} INFO - +---+-----------+--------------+------------------+-------------+---------------+-------------------+----------+
[2025-04-22T17:21:21.010+0000] {subprocess.py:93} INFO - | op|    User ID|Transaction ID|            Amount|       Vendor|        Sources|               Time|      date|
[2025-04-22T17:21:21.011+0000] {subprocess.py:93} INFO - +---+-----------+--------------+------------------+-------------+---------------+-------------------+----------+
[2025-04-22T17:21:21.011+0000] {subprocess.py:93} INFO - |  c|user_000164|  394545432066| 562.2855544159029|        Sport|    Credit Card|2025-03-04 23:37:13|2025-03-04|
[2025-04-22T17:21:21.012+0000] {subprocess.py:93} INFO - |  c|user_000277|  449042867589|456.89575819694386|Entertainment|    Credit Card|2025-03-04 15:45:45|2025-03-04|
[2025-04-22T17:21:21.013+0000] {subprocess.py:93} INFO - |  c|user_000377|  706808354879|487.05524324450585|     Clothing|     Debit Card|2025-03-04 19:54:39|2025-03-04|
[2025-04-22T17:21:21.013+0000] {subprocess.py:93} INFO - |  c|user_000013|  444635369784|12.916386601969176|Entertainment|    Credit Card|2025-03-04 05:00:48|2025-03-04|
[2025-04-22T17:21:21.013+0000] {subprocess.py:93} INFO - |  c|user_000219|  294551921454| 637.8460262099094|Entertainment|Current Account|2025-03-04 11:56:49|2025-03-04|
[2025-04-22T17:21:21.013+0000] {subprocess.py:93} INFO - +---+-----------+--------------+------------------+-------------+---------------+-------------------+----------+
[2025-04-22T17:21:21.013+0000] {subprocess.py:93} INFO - only showing top 5 rows
[2025-04-22T17:21:21.013+0000] {subprocess.py:93} INFO - 
[2025-04-22T17:21:21.013+0000] {subprocess.py:93} INFO - +-----------+--------------------+------------------+-----------------+------------------+-----------------+---------------+---------------+----------+
[2025-04-22T17:21:21.013+0000] {subprocess.py:93} INFO - |    user_id|num_transactions_l1w|  total_amount_l1w|   avg_amount_l1w|    min_amount_l1w|   max_amount_l1w|num_vendors_l1w|num_sources_l1w|      date|
[2025-04-22T17:21:21.013+0000] {subprocess.py:93} INFO - +-----------+--------------------+------------------+-----------------+------------------+-----------------+---------------+---------------+----------+
[2025-04-22T17:21:21.014+0000] {subprocess.py:93} INFO - |user_000098|                  63| 33134.53873838014|525.9450593393674|12.821291817928493|998.0360121059581|             14|              3|2025-03-11|
[2025-04-22T17:21:21.014+0000] {subprocess.py:93} INFO - |user_000424|                  86|41054.656500028264|477.3797267445147|16.521521963895324|991.1209637348907|             14|              3|2025-03-11|
[2025-04-22T17:21:21.014+0000] {subprocess.py:93} INFO - |user_000372|                  66|36629.953463175814|554.9992948966033|16.789591138629277| 975.267333609821|             14|              3|2025-03-11|
[2025-04-22T17:21:21.014+0000] {subprocess.py:93} INFO - |user_000066|                  80|  41478.8040587762|518.4850507347026|  6.93682704632281|988.6011030301456|             14|              3|2025-03-11|
[2025-04-22T17:21:21.014+0000] {subprocess.py:93} INFO - |user_000113|                  83| 44309.01274105079| 533.843527000612|20.229693088843696|995.8016338407768|             14|              3|2025-03-11|
[2025-04-22T17:21:21.014+0000] {subprocess.py:93} INFO - +-----------+--------------------+------------------+-----------------+------------------+-----------------+---------------+---------------+----------+
[2025-04-22T17:21:21.014+0000] {subprocess.py:93} INFO - only showing top 5 rows
[2025-04-22T17:21:21.014+0000] {subprocess.py:93} INFO - 
[2025-04-22T17:21:21.992+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-22T17:21:21.993+0000] {subprocess.py:93} INFO -   File "/opt/***/external_scripts/2_calculate_features.py", line 178, in <module>
[2025-04-22T17:21:21.994+0000] {subprocess.py:93} INFO -     agg_fts.write \
[2025-04-22T17:21:21.995+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/pyspark/sql/readwriter.py", line 1398, in save
[2025-04-22T17:21:21.996+0000] {subprocess.py:93} INFO -     self._jwrite.save(path)
[2025-04-22T17:21:21.996+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-04-22T17:21:21.996+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/pyspark/errors/exceptions/captured.py", line 169, in deco
[2025-04-22T17:21:21.996+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-04-22T17:21:21.997+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 334, in get_return_value
[2025-04-22T17:21:21.997+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JError: An error occurred while calling o165.save
[2025-04-22T17:21:23.278+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-22T17:21:23.362+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-22T17:21:23.537+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=gen_lxw_fts, task_id=calculate_fts, execution_date=20250310T230000, start_date=20250422T171731, end_date=20250422T172123
[2025-04-22T17:21:23.598+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 146 for task calculate_fts (Bash command failed. The command returned a non-zero exit code 1.; 4276)
[2025-04-22T17:21:23.636+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-22T17:21:23.660+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
