[2025-04-22T17:15:50.969+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_lxw_fts.calculate_fts scheduled__2025-03-09T23:00:00+00:00 [queued]>
[2025-04-22T17:15:51.016+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_lxw_fts.calculate_fts scheduled__2025-03-09T23:00:00+00:00 [queued]>
[2025-04-22T17:15:51.017+0000] {taskinstance.py:2171} INFO - Starting attempt 6 of 7
[2025-04-22T17:15:51.046+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): calculate_fts> on 2025-03-09 23:00:00+00:00
[2025-04-22T17:15:51.056+0000] {standard_task_runner.py:60} INFO - Started process 3912 to run task
[2025-04-22T17:15:51.066+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_lxw_fts', 'calculate_fts', 'scheduled__2025-03-09T23:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/gen_lxw_fts.py', '--cfg-path', '/tmp/tmpxaaj4kx2']
[2025-04-22T17:15:51.068+0000] {standard_task_runner.py:88} INFO - Job 145: Subtask calculate_fts
[2025-04-22T17:15:51.171+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_lxw_fts.calculate_fts scheduled__2025-03-09T23:00:00+00:00 [running]> on host 45b38884c639
[2025-04-22T17:15:51.368+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-04-22T17:15:51.492+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_lxw_fts' AIRFLOW_CTX_TASK_ID='calculate_fts' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-09T23:00:00+00:00'
[2025-04-22T17:15:51.495+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-22T17:15:51.495+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/2_calculate_features.py 2025-03-10\n        ']
[2025-04-22T17:15:51.555+0000] {subprocess.py:86} INFO - Output:
[2025-04-22T17:16:09.784+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-04-22T17:16:10.045+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-04-22T17:16:10.050+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-04-22T17:16:10.052+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-04-22T17:16:10.053+0000] {subprocess.py:93} INFO - io.delta#delta-core_2.12 added as a dependency
[2025-04-22T17:16:10.053+0000] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-04-22T17:16:10.054+0000] {subprocess.py:93} INFO - com.amazonaws#aws-java-sdk-bundle added as a dependency
[2025-04-22T17:16:10.054+0000] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2025-04-22T17:16:10.054+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-4168438f-4fad-4c4e-bade-78d7a3ad1515;1.0
[2025-04-22T17:16:10.055+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-04-22T17:16:10.763+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.4.1 in central
[2025-04-22T17:16:10.917+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.4.1 in central
[2025-04-22T17:16:10.974+0000] {subprocess.py:93} INFO - 	found org.apache.kafka#kafka-clients;3.3.2 in central
[2025-04-22T17:16:11.061+0000] {subprocess.py:93} INFO - 	found org.lz4#lz4-java;1.8.0 in central
[2025-04-22T17:16:11.118+0000] {subprocess.py:93} INFO - 	found org.xerial.snappy#snappy-java;1.1.10.1 in central
[2025-04-22T17:16:11.225+0000] {subprocess.py:93} INFO - 	found org.slf4j#slf4j-api;2.0.6 in central
[2025-04-22T17:16:11.292+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2025-04-22T17:16:11.364+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.4 in central
[2025-04-22T17:16:11.411+0000] {subprocess.py:93} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2025-04-22T17:16:11.527+0000] {subprocess.py:93} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-04-22T17:16:11.624+0000] {subprocess.py:93} INFO - 	found org.apache.commons#commons-pool2;2.11.1 in central
[2025-04-22T17:16:11.667+0000] {subprocess.py:93} INFO - 	found io.delta#delta-core_2.12;2.4.0 in central
[2025-04-22T17:16:11.704+0000] {subprocess.py:93} INFO - 	found io.delta#delta-storage;2.4.0 in central
[2025-04-22T17:16:11.715+0000] {subprocess.py:93} INFO - 	found org.antlr#antlr4-runtime;4.9.3 in central
[2025-04-22T17:16:11.748+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.2 in central
[2025-04-22T17:16:11.783+0000] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2025-04-22T17:16:11.812+0000] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.12.261 in central
[2025-04-22T17:16:11.843+0000] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.5.1 in central
[2025-04-22T17:16:11.856+0000] {subprocess.py:93} INFO - 	found org.checkerframework#checker-qual;3.5.0 in central
[2025-04-22T17:16:11.946+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 1833ms :: artifacts dl 59ms
[2025-04-22T17:16:11.948+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-04-22T17:16:11.949+0000] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.12.261 from central in [default]
[2025-04-22T17:16:11.950+0000] {subprocess.py:93} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-04-22T17:16:11.951+0000] {subprocess.py:93} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2025-04-22T17:16:11.951+0000] {subprocess.py:93} INFO - 	io.delta#delta-core_2.12;2.4.0 from central in [default]
[2025-04-22T17:16:11.952+0000] {subprocess.py:93} INFO - 	io.delta#delta-storage;2.4.0 from central in [default]
[2025-04-22T17:16:11.952+0000] {subprocess.py:93} INFO - 	org.antlr#antlr4-runtime;4.9.3 from central in [default]
[2025-04-22T17:16:11.953+0000] {subprocess.py:93} INFO - 	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-04-22T17:16:11.953+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.2 from central in [default]
[2025-04-22T17:16:11.954+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.4 from central in [default]
[2025-04-22T17:16:11.954+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.4 from central in [default]
[2025-04-22T17:16:11.954+0000] {subprocess.py:93} INFO - 	org.apache.kafka#kafka-clients;3.3.2 from central in [default]
[2025-04-22T17:16:11.955+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.4.1 from central in [default]
[2025-04-22T17:16:11.955+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.4.1 from central in [default]
[2025-04-22T17:16:11.956+0000] {subprocess.py:93} INFO - 	org.checkerframework#checker-qual;3.5.0 from central in [default]
[2025-04-22T17:16:11.956+0000] {subprocess.py:93} INFO - 	org.lz4#lz4-java;1.8.0 from central in [default]
[2025-04-22T17:16:11.957+0000] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.5.1 from central in [default]
[2025-04-22T17:16:11.957+0000] {subprocess.py:93} INFO - 	org.slf4j#slf4j-api;2.0.6 from central in [default]
[2025-04-22T17:16:11.958+0000] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2025-04-22T17:16:11.958+0000] {subprocess.py:93} INFO - 	org.xerial.snappy#snappy-java;1.1.10.1 from central in [default]
[2025-04-22T17:16:11.959+0000] {subprocess.py:93} INFO - 	:: evicted modules:
[2025-04-22T17:16:11.959+0000] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.11.1026 by [com.amazonaws#aws-java-sdk-bundle;1.12.261] in [default]
[2025-04-22T17:16:11.959+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-04-22T17:16:11.960+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-04-22T17:16:11.960+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-04-22T17:16:11.961+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-04-22T17:16:11.961+0000] {subprocess.py:93} INFO - 	|      default     |   20  |   0   |   0   |   1   ||   19  |   0   |
[2025-04-22T17:16:11.961+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-04-22T17:16:11.962+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-4168438f-4fad-4c4e-bade-78d7a3ad1515
[2025-04-22T17:16:11.962+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-04-22T17:16:11.982+0000] {subprocess.py:93} INFO - 	0 artifacts copied, 19 already retrieved (0kB/15ms)
[2025-04-22T17:16:13.298+0000] {subprocess.py:93} INFO - 25/04/22 17:16:13 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-04-22T17:16:14.252+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-04-22T17:16:14.253+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-04-22T17:16:50.128+0000] {subprocess.py:93} INFO - 25/04/22 17:16:50 ERROR Inbox: Ignoring error
[2025-04-22T17:16:50.167+0000] {subprocess.py:93} INFO - java.lang.NullPointerException
[2025-04-22T17:16:50.167+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:600)
[2025-04-22T17:16:50.167+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:123)
[2025-04-22T17:16:50.168+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2025-04-22T17:16:50.168+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2025-04-22T17:16:50.168+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2025-04-22T17:16:50.168+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2025-04-22T17:16:50.168+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2025-04-22T17:16:50.168+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-04-22T17:16:50.169+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-04-22T17:16:50.169+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-04-22T17:16:50.169+0000] {subprocess.py:93} INFO - 25/04/22 17:16:50 WARN Executor: Issue communicating with driver in heartbeater
[2025-04-22T17:16:50.169+0000] {subprocess.py:93} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-04-22T17:16:50.169+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
[2025-04-22T17:16:50.169+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2025-04-22T17:16:50.171+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
[2025-04-22T17:16:50.171+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
[2025-04-22T17:16:50.171+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
[2025-04-22T17:16:50.171+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:641)
[2025-04-22T17:16:50.178+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1111)
[2025-04-22T17:16:50.179+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:244)
[2025-04-22T17:16:50.179+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-22T17:16:50.180+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2088)
[2025-04-22T17:16:50.180+0000] {subprocess.py:93} INFO - 	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
[2025-04-22T17:16:50.180+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2025-04-22T17:16:50.180+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[2025-04-22T17:16:50.181+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[2025-04-22T17:16:50.181+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-04-22T17:16:50.181+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-04-22T17:16:50.181+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-04-22T17:16:50.181+0000] {subprocess.py:93} INFO - Caused by: java.lang.NullPointerException
[2025-04-22T17:16:50.183+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:600)
[2025-04-22T17:16:50.184+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:123)
[2025-04-22T17:16:50.186+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2025-04-22T17:16:50.187+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2025-04-22T17:16:50.187+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2025-04-22T17:16:50.187+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2025-04-22T17:16:50.187+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2025-04-22T17:16:50.187+0000] {subprocess.py:93} INFO - 	... 3 more
[2025-04-22T17:16:59.556+0000] {subprocess.py:93} INFO - 25/04/22 17:16:59 ERROR Inbox: Ignoring error
[2025-04-22T17:16:59.583+0000] {subprocess.py:93} INFO - java.lang.NullPointerException
[2025-04-22T17:16:59.583+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:600)
[2025-04-22T17:16:59.584+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:123)
[2025-04-22T17:16:59.584+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2025-04-22T17:16:59.584+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2025-04-22T17:16:59.584+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2025-04-22T17:16:59.584+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2025-04-22T17:16:59.584+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2025-04-22T17:16:59.585+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-04-22T17:16:59.585+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-04-22T17:16:59.585+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-04-22T17:16:59.585+0000] {subprocess.py:93} INFO - 25/04/22 17:16:59 WARN Executor: Issue communicating with driver in heartbeater
[2025-04-22T17:16:59.585+0000] {subprocess.py:93} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-04-22T17:16:59.585+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
[2025-04-22T17:16:59.585+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2025-04-22T17:16:59.585+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
[2025-04-22T17:16:59.592+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
[2025-04-22T17:16:59.595+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
[2025-04-22T17:16:59.596+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:641)
[2025-04-22T17:16:59.596+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1111)
[2025-04-22T17:16:59.598+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:244)
[2025-04-22T17:16:59.598+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-22T17:16:59.598+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2088)
[2025-04-22T17:16:59.598+0000] {subprocess.py:93} INFO - 	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
[2025-04-22T17:16:59.598+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2025-04-22T17:16:59.598+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[2025-04-22T17:16:59.598+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[2025-04-22T17:16:59.599+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-04-22T17:16:59.599+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-04-22T17:16:59.599+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-04-22T17:16:59.600+0000] {subprocess.py:93} INFO - Caused by: java.lang.NullPointerException
[2025-04-22T17:16:59.600+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:600)
[2025-04-22T17:16:59.600+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:123)
[2025-04-22T17:16:59.600+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2025-04-22T17:16:59.600+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2025-04-22T17:16:59.600+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2025-04-22T17:16:59.600+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2025-04-22T17:16:59.600+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2025-04-22T17:16:59.600+0000] {subprocess.py:93} INFO - 	... 3 more
[2025-04-22T17:17:09.524+0000] {subprocess.py:93} INFO - 25/04/22 17:17:09 ERROR Inbox: Ignoring error
[2025-04-22T17:17:09.543+0000] {subprocess.py:93} INFO - java.lang.NullPointerException
[2025-04-22T17:17:09.545+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:600)
[2025-04-22T17:17:09.545+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:123)
[2025-04-22T17:17:09.545+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2025-04-22T17:17:09.545+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2025-04-22T17:17:09.545+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2025-04-22T17:17:09.546+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2025-04-22T17:17:09.546+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2025-04-22T17:17:09.546+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-04-22T17:17:09.546+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-04-22T17:17:09.546+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-04-22T17:17:09.550+0000] {subprocess.py:93} INFO - 25/04/22 17:17:09 WARN Executor: Issue communicating with driver in heartbeater
[2025-04-22T17:17:09.551+0000] {subprocess.py:93} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-04-22T17:17:09.551+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
[2025-04-22T17:17:09.551+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2025-04-22T17:17:09.551+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
[2025-04-22T17:17:09.551+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
[2025-04-22T17:17:09.551+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
[2025-04-22T17:17:09.551+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:641)
[2025-04-22T17:17:09.551+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1111)
[2025-04-22T17:17:09.552+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:244)
[2025-04-22T17:17:09.552+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-22T17:17:09.552+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2088)
[2025-04-22T17:17:09.552+0000] {subprocess.py:93} INFO - 	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
[2025-04-22T17:17:09.552+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2025-04-22T17:17:09.552+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[2025-04-22T17:17:09.552+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[2025-04-22T17:17:09.552+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-04-22T17:17:09.552+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-04-22T17:17:09.552+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-04-22T17:17:09.552+0000] {subprocess.py:93} INFO - Caused by: java.lang.NullPointerException
[2025-04-22T17:17:09.553+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:600)
[2025-04-22T17:17:09.553+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:123)
[2025-04-22T17:17:09.553+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2025-04-22T17:17:09.553+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2025-04-22T17:17:09.553+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2025-04-22T17:17:09.554+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2025-04-22T17:17:09.554+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2025-04-22T17:17:09.554+0000] {subprocess.py:93} INFO - 	... 3 more
[2025-04-22T17:17:19.684+0000] {subprocess.py:93} INFO - 25/04/22 17:17:19 WARN Executor: Issue communicating with driver in heartbeater
[2025-04-22T17:17:19.689+0000] {subprocess.py:93} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-04-22T17:17:19.689+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
[2025-04-22T17:17:19.689+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2025-04-22T17:17:19.689+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
[2025-04-22T17:17:19.689+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
[2025-04-22T17:17:19.690+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
[2025-04-22T17:17:19.690+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:641)
[2025-04-22T17:17:19.695+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1111)
[2025-04-22T17:17:19.696+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:244)
[2025-04-22T17:17:19.696+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-22T17:17:19.696+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2088)
[2025-04-22T17:17:19.696+0000] {subprocess.py:93} INFO - 	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
[2025-04-22T17:17:19.697+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2025-04-22T17:17:19.697+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[2025-04-22T17:17:19.697+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[2025-04-22T17:17:19.697+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-04-22T17:17:19.697+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-04-22T17:17:19.697+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-04-22T17:17:19.697+0000] {subprocess.py:93} INFO - Caused by: java.lang.NullPointerException
[2025-04-22T17:17:19.697+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:600)
[2025-04-22T17:17:19.698+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:123)
[2025-04-22T17:17:19.698+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2025-04-22T17:17:19.698+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2025-04-22T17:17:19.698+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2025-04-22T17:17:19.698+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2025-04-22T17:17:19.698+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2025-04-22T17:17:19.698+0000] {subprocess.py:93} INFO - 	... 3 more
[2025-04-22T17:17:19.698+0000] {subprocess.py:93} INFO - 25/04/22 17:17:19 ERROR Inbox: Ignoring error
[2025-04-22T17:17:19.698+0000] {subprocess.py:93} INFO - java.lang.NullPointerException
[2025-04-22T17:17:19.698+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:600)
[2025-04-22T17:17:19.698+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:123)
[2025-04-22T17:17:19.699+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2025-04-22T17:17:19.699+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2025-04-22T17:17:19.699+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2025-04-22T17:17:19.699+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2025-04-22T17:17:19.699+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2025-04-22T17:17:19.699+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-04-22T17:17:19.699+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-04-22T17:17:19.699+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-04-22T17:17:32.547+0000] {subprocess.py:93} INFO - 25/04/22 17:17:32 WARN SQLConf: The SQL config 'spark.sql.execution.arrow.fallback.enabled' has been deprecated in Spark v3.0 and may be removed in the future. Use 'spark.sql.execution.arrow.pyspark.fallback.enabled' instead of it.
[2025-04-22T17:17:32.556+0000] {subprocess.py:93} INFO - 25/04/22 17:17:32 WARN SQLConf: The SQL config 'spark.sql.execution.arrow.fallback.enabled' has been deprecated in Spark v3.0 and may be removed in the future. Use 'spark.sql.execution.arrow.pyspark.fallback.enabled' instead of it.
[2025-04-22T17:17:32.556+0000] {subprocess.py:93} INFO - 25/04/22 17:17:32 WARN SQLConf: The SQL config 'spark.sql.execution.arrow.fallback.enabled' has been deprecated in Spark v3.0 and may be removed in the future. Use 'spark.sql.execution.arrow.pyspark.fallback.enabled' instead of it.
[2025-04-22T17:17:53.925+0000] {subprocess.py:93} INFO - 25/04/22 17:17:53 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:18:03.890+0000] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 0) / 1][Stage 0:>                                                          (0 + 1) / 1]                                                                                25/04/22 17:18:03 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:18:04.236+0000] {subprocess.py:93} INFO - 25/04/22 17:18:04 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:18:31.505+0000] {subprocess.py:93} INFO - [Stage 1:>                  (0 + 1) / 1][Stage 2:>                  (0 + 1) / 1][Stage 1:>                                                          (0 + 1) / 1][Stage 4:>                                                          (0 + 1) / 1]                                                                                25/04/22 17:18:31 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:18:31.884+0000] {subprocess.py:93} INFO - 25/04/22 17:18:31 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:18:48.656+0000] {subprocess.py:93} INFO - [Stage 5:>                  (0 + 1) / 1][Stage 6:>                  (0 + 1) / 1][Stage 5:>                                                          (0 + 1) / 1][Stage 8:>                                                          (0 + 1) / 1]                                                                                25/04/22 17:18:48 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:18:48.742+0000] {subprocess.py:93} INFO - 25/04/22 17:18:48 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:19:14.408+0000] {subprocess.py:93} INFO - [Stage 16:>                                                         (0 + 1) / 1][Stage 16:>                 (0 + 1) / 1][Stage 17:>                 (0 + 1) / 1][Stage 16:>                                                         (0 + 1) / 1][Stage 19:>                                                         (0 + 5) / 5][Stage 19:=======================>                                  (2 + 3) / 5][Stage 22:>                                                         (0 + 1) / 1]                                                                                25/04/22 17:19:14 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2025-04-22T17:19:23.213+0000] {subprocess.py:93} INFO - 25/04/22 17:19:23 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:19:24.246+0000] {subprocess.py:93} INFO - 25/04/22 17:19:24 WARN AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-04-22T17:19:38.351+0000] {subprocess.py:93} INFO - ERROR:root:Exception while sending command.
[2025-04-22T17:19:38.376+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-22T17:19:38.377+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 516, in send_command
[2025-04-22T17:19:38.378+0000] {subprocess.py:93} INFO -     raise Py4JNetworkError("Answer from Java side is empty")
[2025-04-22T17:19:38.378+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2025-04-22T17:19:38.379+0000] {subprocess.py:93} INFO - 
[2025-04-22T17:19:38.380+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2025-04-22T17:19:38.380+0000] {subprocess.py:93} INFO - 
[2025-04-22T17:19:38.380+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-22T17:19:38.380+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1038, in send_command
[2025-04-22T17:19:38.380+0000] {subprocess.py:93} INFO -     response = connection.send_command(command)
[2025-04-22T17:19:38.380+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 539, in send_command
[2025-04-22T17:19:38.383+0000] {subprocess.py:93} INFO -     raise Py4JNetworkError(
[2025-04-22T17:19:38.384+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2025-04-22T17:19:38.384+0000] {subprocess.py:93} INFO - 2025-03-03 2025-03-10
[2025-04-22T17:19:38.385+0000] {subprocess.py:93} INFO - Spark session initialized
[2025-04-22T17:19:38.390+0000] {subprocess.py:93} INFO - +------+--------------------+--------------------+---+-------------+-----------+
[2025-04-22T17:19:38.390+0000] {subprocess.py:93} INFO - |before|               after|              source| op|        ts_ms|transaction|
[2025-04-22T17:19:38.391+0000] {subprocess.py:93} INFO - +------+--------------------+--------------------+---+-------------+-----------+
[2025-04-22T17:19:38.391+0000] {subprocess.py:93} INFO - |  null|{1, user_000461, ...|{2.3.4.Final, pos...|  c|1745341450710|       null|
[2025-04-22T17:19:38.399+0000] {subprocess.py:93} INFO - |  null|{2, user_000113, ...|{2.3.4.Final, pos...|  c|1745341450735|       null|
[2025-04-22T17:19:38.399+0000] {subprocess.py:93} INFO - |  null|{3, user_000286, ...|{2.3.4.Final, pos...|  c|1745341450737|       null|
[2025-04-22T17:19:38.400+0000] {subprocess.py:93} INFO - |  null|{4, user_000402, ...|{2.3.4.Final, pos...|  c|1745341450738|       null|
[2025-04-22T17:19:38.400+0000] {subprocess.py:93} INFO - |  null|{5, user_000126, ...|{2.3.4.Final, pos...|  c|1745341450739|       null|
[2025-04-22T17:19:38.400+0000] {subprocess.py:93} INFO - +------+--------------------+--------------------+---+-------------+-----------+
[2025-04-22T17:19:38.400+0000] {subprocess.py:93} INFO - only showing top 5 rows
[2025-04-22T17:19:38.400+0000] {subprocess.py:93} INFO - 
[2025-04-22T17:19:38.400+0000] {subprocess.py:93} INFO - +---+-----------+--------------+------------------+---------------+---------------+-------------------+----------+
[2025-04-22T17:19:38.400+0000] {subprocess.py:93} INFO - | op|    User ID|Transaction ID|            Amount|         Vendor|        Sources|               Time|      date|
[2025-04-22T17:19:38.400+0000] {subprocess.py:93} INFO - +---+-----------+--------------+------------------+---------------+---------------+-------------------+----------+
[2025-04-22T17:19:38.401+0000] {subprocess.py:93} INFO - |  c|user_000325|  642845616831| 899.7274500310243|  Entertainment|Current Account|2025-03-03 07:10:35|2025-03-03|
[2025-04-22T17:19:38.401+0000] {subprocess.py:93} INFO - |  c|user_000491|  914150072068|394.29587540660526|Online Shopping|Current Account|2025-03-03 22:08:00|2025-03-03|
[2025-04-22T17:19:38.401+0000] {subprocess.py:93} INFO - |  c|user_000261|  416199368382| 977.3242123870463|       Clothing|Current Account|2025-03-03 17:37:45|2025-03-03|
[2025-04-22T17:19:38.401+0000] {subprocess.py:93} INFO - |  c|user_000456|  663335223071| 634.1293714254631|       Clothing|Current Account|2025-03-03 01:44:42|2025-03-03|
[2025-04-22T17:19:38.401+0000] {subprocess.py:93} INFO - |  c|user_000431|  375031370220|  234.121769428575|  Entertainment|Current Account|2025-03-03 16:14:22|2025-03-03|
[2025-04-22T17:19:38.402+0000] {subprocess.py:93} INFO - +---+-----------+--------------+------------------+---------------+---------------+-------------------+----------+
[2025-04-22T17:19:38.402+0000] {subprocess.py:93} INFO - only showing top 5 rows
[2025-04-22T17:19:38.402+0000] {subprocess.py:93} INFO - 
[2025-04-22T17:19:38.402+0000] {subprocess.py:93} INFO - +-----------+--------------------+------------------+------------------+------------------+-----------------+---------------+---------------+----------+
[2025-04-22T17:19:38.402+0000] {subprocess.py:93} INFO - |    user_id|num_transactions_l1w|  total_amount_l1w|    avg_amount_l1w|    min_amount_l1w|   max_amount_l1w|num_vendors_l1w|num_sources_l1w|      date|
[2025-04-22T17:19:38.402+0000] {subprocess.py:93} INFO - +-----------+--------------------+------------------+------------------+------------------+-----------------+---------------+---------------+----------+
[2025-04-22T17:19:38.402+0000] {subprocess.py:93} INFO - |user_000098|                  63|  32950.2574568445| 523.0199596324524| 56.67791262018449|998.0360121059581|             14|              3|2025-03-10|
[2025-04-22T17:19:38.403+0000] {subprocess.py:93} INFO - |user_000424|                  89| 42879.10721560002|481.78772152359574|16.521521963895324|977.4093263719208|             14|              3|2025-03-10|
[2025-04-22T17:19:38.403+0000] {subprocess.py:93} INFO - |user_000372|                  66| 36756.14832884525| 556.9113383158372|16.789591138629277|980.8410055522904|             14|              3|2025-03-10|
[2025-04-22T17:19:38.403+0000] {subprocess.py:93} INFO - |user_000066|                  87| 42427.89592331814|487.67696463584065| 1.651592325326979|988.6011030301456|             14|              3|2025-03-10|
[2025-04-22T17:19:38.403+0000] {subprocess.py:93} INFO - |user_000113|                  85|45939.026809959796| 540.4591389407035|20.229693088843696|995.8016338407768|             14|              3|2025-03-10|
[2025-04-22T17:19:38.403+0000] {subprocess.py:93} INFO - +-----------+--------------------+------------------+------------------+------------------+-----------------+---------------+---------------+----------+
[2025-04-22T17:19:38.404+0000] {subprocess.py:93} INFO - only showing top 5 rows
[2025-04-22T17:19:38.404+0000] {subprocess.py:93} INFO - 
[2025-04-22T17:19:38.631+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-22T17:19:38.631+0000] {subprocess.py:93} INFO -   File "/opt/***/external_scripts/2_calculate_features.py", line 178, in <module>
[2025-04-22T17:19:38.632+0000] {subprocess.py:93} INFO -     agg_fts.write \
[2025-04-22T17:19:38.632+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/pyspark/sql/readwriter.py", line 1398, in save
[2025-04-22T17:19:38.632+0000] {subprocess.py:93} INFO -     self._jwrite.save(path)
[2025-04-22T17:19:38.632+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-04-22T17:19:38.632+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/pyspark/errors/exceptions/captured.py", line 169, in deco
[2025-04-22T17:19:38.635+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-04-22T17:19:38.638+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 334, in get_return_value
[2025-04-22T17:19:38.639+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JError: An error occurred while calling o165.save
[2025-04-22T17:19:39.579+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-22T17:19:40.363+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-22T17:19:40.475+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=gen_lxw_fts, task_id=calculate_fts, execution_date=20250309T230000, start_date=20250422T171550, end_date=20250422T171940
[2025-04-22T17:19:40.552+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 145 for task calculate_fts (Bash command failed. The command returned a non-zero exit code 1.; 3912)
[2025-04-22T17:19:40.589+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-22T17:19:40.644+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
