2025-04-22 17:04:10,203 - __main__ - INFO - Successfully inserted 5000 rows into transaction_data table at 2025-03-02
2025-04-22 17:04:10,207 - __main__ - INFO - Checking table transaction_data contains 5000 rows
2025-04-22 17:04:10,208 - __main__ - INFO - Data generation and insertion complete at 2025-03-02
2025-04-28 17:08:35,424 - __main__ - ERROR - Error inserting data into PostgreSQL: (psycopg2.errors.DuplicateTable) relation "transaction_data" already exists

[SQL: 
CREATE TABLE public.transaction_data (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	"User ID" VARCHAR(255), 
	"Transaction ID" VARCHAR(255), 
	"Amount" FLOAT, 
	"Vendor" VARCHAR(255), 
	"Sources" VARCHAR(255), 
	"Time" VARCHAR(255), 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
2025-04-28 17:09:27,526 - __main__ - INFO - Successfully inserted 5000 rows into transaction_data table at 2025-03-02
2025-04-28 17:09:27,535 - __main__ - INFO - Checking table transaction_data contains 80000 rows
2025-04-28 17:09:27,536 - __main__ - INFO - Data generation and insertion complete at 2025-03-02
