[2025-04-01T17:47:04.094+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-05T22:00:00+00:00 [queued]>
[2025-04-01T17:47:04.108+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-05T22:00:00+00:00 [queued]>
[2025-04-01T17:47:04.110+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-01T17:47:04.127+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-05 22:00:00+00:00
[2025-04-01T17:47:04.136+0000] {standard_task_runner.py:60} INFO - Started process 723 to run task
[2025-04-01T17:47:04.141+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-05T22:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmppje8wnyk']
[2025-04-01T17:47:04.142+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask gen_data_daily
[2025-04-01T17:47:04.208+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-05T22:00:00+00:00 [running]> on host 0b0a92439eeb
[2025-04-01T17:47:04.372+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-05T22:00:00+00:00'
[2025-04-01T17:47:04.376+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-01T17:47:04.377+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-06\n        ']
[2025-04-01T17:47:04.393+0000] {subprocess.py:86} INFO - Output:
[2025-04-01T17:47:05.422+0000] {subprocess.py:93} INFO - Successfully inserted 5000 rows into transaction_data table at 2025-03-06
[2025-04-01T17:47:05.422+0000] {subprocess.py:93} INFO - Table contains 25000 rows
[2025-04-01T17:47:05.422+0000] {subprocess.py:93} INFO - Data generation and insertion complete at 2025-03-06
[2025-04-01T17:47:05.538+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-01T17:47:05.580+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250305T220000, start_date=20250401T174704, end_date=20250401T174705
[2025-04-01T17:47:05.620+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-01T17:47:05.647+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T17:08:41.580+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-05T22:00:00+00:00 [queued]>
[2025-04-28T17:08:41.632+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-05T22:00:00+00:00 [queued]>
[2025-04-28T17:08:41.633+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-28T17:08:41.670+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-05 22:00:00+00:00
[2025-04-28T17:08:41.682+0000] {standard_task_runner.py:60} INFO - Started process 44281 to run task
[2025-04-28T17:08:41.693+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-05T22:00:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpeq6g7_55']
[2025-04-28T17:08:41.703+0000] {standard_task_runner.py:88} INFO - Job 158: Subtask gen_data_daily
[2025-04-28T17:08:41.844+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-05T22:00:00+00:00 [running]> on host 45b38884c639
[2025-04-28T17:08:41.925+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-04-28T17:08:42.018+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-05T22:00:00+00:00'
[2025-04-28T17:08:42.020+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-28T17:08:42.020+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/step_1_1_gen_transaction_data.py 2025-03-06\n        ']
[2025-04-28T17:08:42.056+0000] {subprocess.py:86} INFO - Output:
[2025-04-28T17:08:44.159+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-28T17:08:44.229+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250305T220000, start_date=20250428T170841, end_date=20250428T170844
[2025-04-28T17:08:44.476+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T17:08:44.550+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
