[2025-04-01T17:46:58.937+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-03T22:00:00+00:00 [queued]>
[2025-04-01T17:46:58.954+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-03T22:00:00+00:00 [queued]>
[2025-04-01T17:46:58.955+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-01T17:46:58.980+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-03 22:00:00+00:00
[2025-04-01T17:46:58.988+0000] {standard_task_runner.py:60} INFO - Started process 701 to run task
[2025-04-01T17:46:58.995+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-03T22:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmppg6a3hup']
[2025-04-01T17:46:58.997+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask gen_data_daily
[2025-04-01T17:46:59.103+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-03T22:00:00+00:00 [running]> on host 0b0a92439eeb
[2025-04-01T17:46:59.309+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T22:00:00+00:00'
[2025-04-01T17:46:59.310+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-01T17:46:59.311+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-04\n        ']
[2025-04-01T17:46:59.328+0000] {subprocess.py:86} INFO - Output:
[2025-04-01T17:47:00.481+0000] {subprocess.py:93} INFO - Successfully inserted 5000 rows into transaction_data table at 2025-03-04
[2025-04-01T17:47:00.482+0000] {subprocess.py:93} INFO - Table contains 15000 rows
[2025-04-01T17:47:00.482+0000] {subprocess.py:93} INFO - Data generation and insertion complete at 2025-03-04
[2025-04-01T17:47:00.607+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-01T17:47:00.643+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250303T220000, start_date=20250401T174658, end_date=20250401T174700
[2025-04-01T17:47:00.680+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-01T17:47:00.713+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T17:08:37.139+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-03T22:00:00+00:00 [queued]>
[2025-04-28T17:08:37.189+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-03T22:00:00+00:00 [queued]>
[2025-04-28T17:08:37.190+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-28T17:08:37.225+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-03 22:00:00+00:00
[2025-04-28T17:08:37.231+0000] {standard_task_runner.py:60} INFO - Started process 44258 to run task
[2025-04-28T17:08:37.238+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-03T22:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmprdnegb32']
[2025-04-28T17:08:37.242+0000] {standard_task_runner.py:88} INFO - Job 155: Subtask gen_data_daily
[2025-04-28T17:08:37.350+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-03T22:00:00+00:00 [running]> on host 45b38884c639
[2025-04-28T17:08:37.435+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-04-28T17:08:37.502+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T22:00:00+00:00'
[2025-04-28T17:08:37.504+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-28T17:08:37.508+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/step_1_1_gen_transaction_data.py 2025-03-04\n        ']
[2025-04-28T17:08:37.532+0000] {subprocess.py:86} INFO - Output:
[2025-04-28T17:08:39.340+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-28T17:08:39.529+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250303T220000, start_date=20250428T170837, end_date=20250428T170839
[2025-04-28T17:08:39.698+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T17:08:39.847+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
