[2025-04-01T17:47:10.016+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-07T22:00:00+00:00 [queued]>
[2025-04-01T17:47:10.024+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-07T22:00:00+00:00 [queued]>
[2025-04-01T17:47:10.025+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-01T17:47:10.036+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-07 22:00:00+00:00
[2025-04-01T17:47:10.042+0000] {standard_task_runner.py:60} INFO - Started process 745 to run task
[2025-04-01T17:47:10.050+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-07T22:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpiyo0m4h7']
[2025-04-01T17:47:10.051+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask gen_data_daily
[2025-04-01T17:47:10.128+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-07T22:00:00+00:00 [running]> on host 0b0a92439eeb
[2025-04-01T17:47:10.289+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-07T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-07T22:00:00+00:00'
[2025-04-01T17:47:10.291+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-01T17:47:10.292+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-08\n        ']
[2025-04-01T17:47:10.309+0000] {subprocess.py:86} INFO - Output:
[2025-04-01T17:47:11.338+0000] {subprocess.py:93} INFO - Successfully inserted 5000 rows into transaction_data table at 2025-03-08
[2025-04-01T17:47:11.339+0000] {subprocess.py:93} INFO - Table contains 35000 rows
[2025-04-01T17:47:11.339+0000] {subprocess.py:93} INFO - Data generation and insertion complete at 2025-03-08
[2025-04-01T17:47:11.477+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-01T17:47:11.528+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250307T220000, start_date=20250401T174710, end_date=20250401T174711
[2025-04-01T17:47:11.572+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-01T17:47:11.603+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T17:08:45.376+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-07T22:00:00+00:00 [queued]>
[2025-04-28T17:08:45.406+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-07T22:00:00+00:00 [queued]>
[2025-04-28T17:08:45.406+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-28T17:08:45.455+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-07 22:00:00+00:00
[2025-04-28T17:08:45.475+0000] {standard_task_runner.py:60} INFO - Started process 44302 to run task
[2025-04-28T17:08:45.481+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-07T22:00:00+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpxc87zcnw']
[2025-04-28T17:08:45.483+0000] {standard_task_runner.py:88} INFO - Job 159: Subtask gen_data_daily
[2025-04-28T17:08:45.619+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-07T22:00:00+00:00 [running]> on host 45b38884c639
[2025-04-28T17:08:45.882+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-04-28T17:08:45.970+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-07T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-07T22:00:00+00:00'
[2025-04-28T17:08:45.972+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-28T17:08:45.978+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/step_1_1_gen_transaction_data.py 2025-03-08\n        ']
[2025-04-28T17:08:46.012+0000] {subprocess.py:86} INFO - Output:
[2025-04-28T17:08:47.689+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-28T17:08:48.252+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250307T220000, start_date=20250428T170845, end_date=20250428T170848
[2025-04-28T17:08:48.467+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T17:08:49.171+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
