[2025-04-01T17:47:19.802+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-11T22:00:00+00:00 [queued]>
[2025-04-01T17:47:19.816+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-11T22:00:00+00:00 [queued]>
[2025-04-01T17:47:19.816+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-01T17:47:19.834+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-11 22:00:00+00:00
[2025-04-01T17:47:19.841+0000] {standard_task_runner.py:60} INFO - Started process 797 to run task
[2025-04-01T17:47:19.845+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-11T22:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpizv1hcs0']
[2025-04-01T17:47:19.846+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask gen_data_daily
[2025-04-01T17:47:19.936+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-11T22:00:00+00:00 [running]> on host 0b0a92439eeb
[2025-04-01T17:47:20.074+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-11T22:00:00+00:00'
[2025-04-01T17:47:20.076+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-01T17:47:20.077+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-12\n        ']
[2025-04-01T17:47:20.093+0000] {subprocess.py:86} INFO - Output:
[2025-04-01T17:47:21.149+0000] {subprocess.py:93} INFO - Successfully inserted 5000 rows into transaction_data table at 2025-03-12
[2025-04-01T17:47:21.150+0000] {subprocess.py:93} INFO - Table contains 55000 rows
[2025-04-01T17:47:21.150+0000] {subprocess.py:93} INFO - Data generation and insertion complete at 2025-03-12
[2025-04-01T17:47:21.270+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-01T17:47:21.306+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250311T220000, start_date=20250401T174719, end_date=20250401T174721
[2025-04-01T17:47:21.345+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-01T17:47:21.371+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T17:08:53.628+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-11T22:00:00+00:00 [queued]>
[2025-04-28T17:08:53.670+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-11T22:00:00+00:00 [queued]>
[2025-04-28T17:08:53.671+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-28T17:08:53.698+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-11 22:00:00+00:00
[2025-04-28T17:08:53.706+0000] {standard_task_runner.py:60} INFO - Started process 44347 to run task
[2025-04-28T17:08:53.714+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-11T22:00:00+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmp7ur8vub8']
[2025-04-28T17:08:53.717+0000] {standard_task_runner.py:88} INFO - Job 164: Subtask gen_data_daily
[2025-04-28T17:08:53.848+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-11T22:00:00+00:00 [running]> on host 45b38884c639
[2025-04-28T17:08:53.944+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-04-28T17:08:54.194+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-11T22:00:00+00:00'
[2025-04-28T17:08:54.205+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-28T17:08:54.206+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/step_1_1_gen_transaction_data.py 2025-03-12\n        ']
[2025-04-28T17:08:54.232+0000] {subprocess.py:86} INFO - Output:
[2025-04-28T17:08:56.496+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-28T17:08:56.622+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250311T220000, start_date=20250428T170853, end_date=20250428T170856
[2025-04-28T17:08:56.674+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T17:08:56.703+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
