[2025-04-01T17:47:17.302+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-10T22:00:00+00:00 [queued]>
[2025-04-01T17:47:17.318+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-10T22:00:00+00:00 [queued]>
[2025-04-01T17:47:17.318+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-01T17:47:17.336+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-10 22:00:00+00:00
[2025-04-01T17:47:17.342+0000] {standard_task_runner.py:60} INFO - Started process 786 to run task
[2025-04-01T17:47:17.346+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-10T22:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpdydxrcmu']
[2025-04-01T17:47:17.347+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask gen_data_daily
[2025-04-01T17:47:17.432+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-10T22:00:00+00:00 [running]> on host 0b0a92439eeb
[2025-04-01T17:47:17.601+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T22:00:00+00:00'
[2025-04-01T17:47:17.604+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-01T17:47:17.605+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-11\n        ']
[2025-04-01T17:47:17.635+0000] {subprocess.py:86} INFO - Output:
[2025-04-01T17:47:18.767+0000] {subprocess.py:93} INFO - Successfully inserted 5000 rows into transaction_data table at 2025-03-11
[2025-04-01T17:47:18.768+0000] {subprocess.py:93} INFO - Table contains 50000 rows
[2025-04-01T17:47:18.768+0000] {subprocess.py:93} INFO - Data generation and insertion complete at 2025-03-11
[2025-04-01T17:47:18.855+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-01T17:47:18.901+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250310T220000, start_date=20250401T174717, end_date=20250401T174718
[2025-04-01T17:47:19.011+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-01T17:47:19.033+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T17:08:50.129+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-10T22:00:00+00:00 [queued]>
[2025-04-28T17:08:50.162+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-10T22:00:00+00:00 [queued]>
[2025-04-28T17:08:50.163+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-28T17:08:50.191+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-10 22:00:00+00:00
[2025-04-28T17:08:50.198+0000] {standard_task_runner.py:60} INFO - Started process 44327 to run task
[2025-04-28T17:08:50.205+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-10T22:00:00+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpuzaibdmb']
[2025-04-28T17:08:50.206+0000] {standard_task_runner.py:88} INFO - Job 162: Subtask gen_data_daily
[2025-04-28T17:08:50.312+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-10T22:00:00+00:00 [running]> on host 45b38884c639
[2025-04-28T17:08:50.411+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-04-28T17:08:50.485+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T22:00:00+00:00'
[2025-04-28T17:08:50.487+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-28T17:08:50.488+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/step_1_1_gen_transaction_data.py 2025-03-11\n        ']
[2025-04-28T17:08:50.510+0000] {subprocess.py:86} INFO - Output:
[2025-04-28T17:08:52.275+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-28T17:08:52.343+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250310T220000, start_date=20250428T170850, end_date=20250428T170852
[2025-04-28T17:08:52.417+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T17:08:52.477+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
