[2025-04-01T17:47:12.315+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-08T22:00:00+00:00 [queued]>
[2025-04-01T17:47:12.329+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-08T22:00:00+00:00 [queued]>
[2025-04-01T17:47:12.329+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-01T17:47:12.350+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-08 22:00:00+00:00
[2025-04-01T17:47:12.358+0000] {standard_task_runner.py:60} INFO - Started process 756 to run task
[2025-04-01T17:47:12.363+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-08T22:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpd1pb345z']
[2025-04-01T17:47:12.364+0000] {standard_task_runner.py:88} INFO - Job 26: Subtask gen_data_daily
[2025-04-01T17:47:12.457+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-08T22:00:00+00:00 [running]> on host 0b0a92439eeb
[2025-04-01T17:47:12.661+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-08T22:00:00+00:00'
[2025-04-01T17:47:12.663+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-01T17:47:12.664+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-09\n        ']
[2025-04-01T17:47:12.683+0000] {subprocess.py:86} INFO - Output:
[2025-04-01T17:47:13.776+0000] {subprocess.py:93} INFO - Successfully inserted 5000 rows into transaction_data table at 2025-03-09
[2025-04-01T17:47:13.777+0000] {subprocess.py:93} INFO - Table contains 40000 rows
[2025-04-01T17:47:13.777+0000] {subprocess.py:93} INFO - Data generation and insertion complete at 2025-03-09
[2025-04-01T17:47:13.931+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-01T17:47:13.977+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250308T220000, start_date=20250401T174712, end_date=20250401T174713
[2025-04-01T17:47:14.051+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-01T17:47:14.084+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T17:08:46.021+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-08T22:00:00+00:00 [queued]>
[2025-04-28T17:08:46.042+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-08T22:00:00+00:00 [queued]>
[2025-04-28T17:08:46.043+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-28T17:08:46.060+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-08 22:00:00+00:00
[2025-04-28T17:08:46.070+0000] {standard_task_runner.py:60} INFO - Started process 44305 to run task
[2025-04-28T17:08:46.079+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-08T22:00:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmptcf7p13r']
[2025-04-28T17:08:46.081+0000] {standard_task_runner.py:88} INFO - Job 160: Subtask gen_data_daily
[2025-04-28T17:08:46.227+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-08T22:00:00+00:00 [running]> on host 45b38884c639
[2025-04-28T17:08:46.325+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-04-28T17:08:46.429+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-08T22:00:00+00:00'
[2025-04-28T17:08:46.431+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-28T17:08:46.432+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/step_1_1_gen_transaction_data.py 2025-03-09\n        ']
[2025-04-28T17:08:46.451+0000] {subprocess.py:86} INFO - Output:
[2025-04-28T17:08:48.831+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-28T17:08:48.968+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250308T220000, start_date=20250428T170846, end_date=20250428T170848
[2025-04-28T17:08:49.165+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T17:08:49.237+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
